name: Build and deploy ASP.NET Core app to Azure Web App - webappnamegoeshere

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore ./MyMvcApp.csproj

      - name: Build
        run: dotnet build ./MyMvcApp.csproj --no-restore

      - name: Test
        run: dotnet test ./MyMvcApp.csproj --no-build --verbosity normal

      - name: dotnet publish
        run: dotnet publish ./MyMvcApp.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'webappnamegoeshere'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.__publishingprofilesecretname__ }}